In [1]:
### tipe data dictionary dan list

trx = {
    "items": [
        {
            "product": "Aqua 500ml",
            "price": 3500,
            "qty": 3
        },
        {
            "product": "Indomie goreng",
            "price": 3000,
            "qty": 12
        },
        {
            "product": "Gula Pasir 1kg",
            "price": 17000,
            "qty": 2
        }
    ],
    "discount": 15,
    "tax": 11
}

print(trx)

{'items': [{'product': 'Aqua 500ml', 'price': 3500, 'qty': 3}, {'product': 'Indomie goreng', 'price': 3000, 'qty': 12}, {'product': 'Gula Pasir 1kg', 'price': 17000, 'qty': 2}], 'discount': 15, 'tax': 11}

In [2]:
students = [
    {
        "nim": 2046363636,
        "nama": "Iwan",
        "semester": 6,
        "hasil": [
            {
                "mata_kuliah": "kecerdasan buatan",
                "hadir": 18,
                "sks": 3,
                "nilai": {
                    "tugas": 75,
                    "uts": 80,
                    "uas": 77
                },
                "total": 0
            },
            {
                "mata_kuliah": "basis data 1",
                "hadir": 20,
                "sks": 3,
                "nilai": {
                    "tugas": 80,
                    "uts": 82,
                    "uas": 67
                },
                "total": 0
            },
            {
                "mata_kuliah": "digital enterpreneur",
                "hadir": 14,
                "sks": 2,
                "nilai": {
                    "tugas": 90,
                    "uts": 82,
                    "uas": 80
                },
                "total": 0
            }
        ]
    },
    {
        "nim": 2046363777,
        "nama": "Saepulloh",
        "semester": 2,
        "hasil": [
            {
                "mata_kuliah": "algoritma & pemrogaman 1",
                "hadir": 20,
                "sks": 3,
                "nilai": {
                    "tugas": 90,
                    "uts": 80,
                    "uas": 70
                },
                "total": 0
            },
            {
                "mata_kuliah": "kalkulus 1",
                "hadir": 21,
                "sks": 3,
                "nilai": {
                    "tugas": 70,
                    "uts": 60,
                    "uas": 67
                },
                "total": 0
            },
            {
                "mata_kuliah": "statistika dan probabilitas",
                "hadir": 13,
                "sks": 2,
                "nilai": {
                    "tugas": 90,
                    "uts": 70,
                    "uas": 88
                },
                "total": 0
            }
        ]
    }
]

In [3]:
bobot_nilai = {"hadir": 10, "tugas": 20, "uts": 30, "uas": 40}
def hitung_nilai(sks, hadir, tugas, uts, uas):
    max_hadir = 0
    if sks == 2:
        max_hadir = 14
    if sks == 3:
        max_hadir = 21
    if not max_hadir:
        print("sks tidak valid")
        return
    # Hitung nilai
    kehadiran = hadir / max_hadir * bobot_nilai["hadir"] / 100
    tugas = tugas / 100 * bobot_nilai["tugas"] / 100
    uts = uts / 100 * bobot_nilai["uts"] / 100
    uas = uas / 100 * bobot_nilai["uas"] / 100
    return round((kehadiran + tugas + uts + uas) * 100, 2)

In [4]:
for student in students:
    for data in student["hasil"]:
        total_nilai = hitung_nilai(data["sks"], data["hadir"], data["nilai"]["tugas"], data["nilai"]["uts"], data["nilai"]["uas"])
        data["total"] = total_nilai

for student in students:
    print(f"Nama: {student['nama']}, Semester: {student['semester']}")
    for data in student["hasil"]:
        print(f"  Mata Kuliah: {data['mata_kuliah']}, Total Nilai: {data['total']}")

Nama: Iwan, Semester: 6
  Mata Kuliah: kecerdasan buatan, Total Nilai: 78.37
  Mata Kuliah: basis data 1, Total Nilai: 76.92
  Mata Kuliah: digital enterpreneur, Total Nilai: 84.6
Nama: Saepulloh, Semester: 2
  Mata Kuliah: algoritma & pemrogaman 1, Total Nilai: 79.52
  Mata Kuliah: kalkulus 1, Total Nilai: 68.8
  Mata Kuliah: statistika dan probabilitas, Total Nilai: 83.49

In [5]:
students

[{'nim': 2046363636,
  'nama': 'Iwan',
  'semester': 6,
  'hasil': [{'mata_kuliah': 'kecerdasan buatan',
    'hadir': 18,
    'sks': 3,
    'nilai': {'tugas': 75, 'uts': 80, 'uas': 77},
    'total': 78.37},
   {'mata_kuliah': 'basis data 1',
    'hadir': 20,
    'sks': 3,
    'nilai': {'tugas': 80, 'uts': 82, 'uas': 67},
    'total': 76.92},
   {'mata_kuliah': 'digital enterpreneur',
    'hadir': 14,
    'sks': 2,
    'nilai': {'tugas': 90, 'uts': 82, 'uas': 80},
    'total': 84.6}]},
 {'nim': 2046363777,
  'nama': 'Saepulloh',
  'semester': 2,
  'hasil': [{'mata_kuliah': 'algoritma & pemrogaman 1',
    'hadir': 20,
    'sks': 3,
    'nilai': {'tugas': 90, 'uts': 80, 'uas': 70},
    'total': 79.52},
   {'mata_kuliah': 'kalkulus 1',
    'hadir': 21,
    'sks': 3,
    'nilai': {'tugas': 70, 'uts': 60, 'uas': 67},
    'total': 68.8},
   {'mata_kuliah': 'statistika dan probabilitas',
    'hadir': 13,
    'sks': 2,
    'nilai': {'tugas': 90, 'uts': 70, 'uas': 88},
    'total': 83.49}]}]